microservicesName:
  ai-content-agent-app:
    isHpaEnabled: true
    autoscalingMinReplicas: 2
    autoscalingMaxReplicas: 2
    nodeSelector:
      label: graviton
    tolerations:
      - effect: NoSchedule
        key: taint
        operator: Equal
        value: graviton
    tolerationsEnabled: true
    nodeSelectorEnabled: true

ingress:
  annotations: {}
  overrideAnnotations:
    alb.ingress.kubernetes.io/group.name: ingress-dev-2 # using load balancer 2
    alb.ingress.kubernetes.io/load-balancer-name: ingress-alb-dev-2

#***********************************************************************************************************#
# ConfigMap Variables #
# Common configurations across all services included in this repo
#***********************************************************************************************************#

configMap:
  data:
    ENV: dev
    PORT: "5000"
    LOG_LEVEL: info
    ENV_REGION: dev
    AI_INFRA_LOG_LEVEL: info
    
    # AWS Configuration
    AWS_SM_REGION: us-west-2

    AGENT_NAME: survey-summary

    ENVIRONMENT: dev

    KAFKA_BOOTSTRAP_ADDRESS: b-3.zeusbasesharedpreprod.68d6s9.c14.kafka.us-west-2.amazonaws.com:9094,b-1.zeusbasesharedpreprod.68d6s9.c14.kafka.us-west-2.amazonaws.com:9094,b-2.zeusbasesharedpreprod.68d6s9.c14.kafka.us-west-2.amazonaws.com:9094

    CONSUMER_TOPIC: Sample_AI_Agent_Topic_Dev
    PRODUCER_TOPIC: Sample_AI_Agent_Topic_2_Dev
    KAFKA_GROUP_ID: survey-summary-crew-consumer
    SECURITY_PROTOCOL: SSL
    MAX_POLL_INTERVAL_MS: "1000"
    MAX_POLL_RECORDS: "1"

    KAFKA_ENABLED: "true"
    KAFKA_TRACES_TOPIC: AI_Trace_Ingestion_Event_Dev

    AWS_SM_VAULT_CONFIG: vault/dev/orion
    AWS_DEFAULT_REGION: us-west-2

    SQL_VAULT_PATH: services/data/infra/dev/static/db/ai_platform_memory
    MONGO_VAULT_PATH: services/data/infra/dev/static/mongo_db/ai_platform_memory
    REDIS_VAULT_PATH: services/data/infra/dev/static/redis/zeus
    LANGFUSE_VAULT_PATH: services/data/llm-orchestrator/dev/static/key/langfuse-v3

    LLM_ENDPOINT: https://api-be.dev.simpplr.xyz/v1/chat/completions
    LLM_RESPONSES_ENDPOINT: https://api-be.dev.simpplr.xyz/v1/responses
    AI_CONFIG_API_BASE_URL: https://api-be.dev.simpplr.xyz
